# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/notation_core",
    "crates/notation_fretted",
    "crates/notation_proto",
    "crates/notation_bevy",
    "apps/notation_viewer",
]

# https://rustwasm.github.io/book/reference/code-size.html
[profile.release]
lto = "thin"
opt-level = 's'
# opt-level = 'z'

[profile.dev]
opt-level = 1


