# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/notation_core",
    "crates/notation_guitar",
    "crates/notation_proto",
    "crates/notation_bevy",
    "apps/notation_viewer",
]
