# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = [
    "crates/notation_core",
    "crates/notation_fretted",
    "crates/notation_proto",
    "crates/notation_midi",
    "crates/notation_dsl",
    "crates/notation_tab",
    "crates/notation_macro",
    "crates/notation_model",
    "crates/notation_bevy",
    "apps/notation_kb",
    "apps/notation_kb_cn",
    "apps/notation_tabs",
    "apps/notation_viewer",
    "apps/notation_viewer_cn",
]

# https://rustwasm.github.io/book/reference/code-size.html
[profile.release]
lto = "thin"
opt-level = 's'
# opt-level = 'z'

[profile.dev]
opt-level = 1

[patch.crates-io]
# winit = { git = "https://github.com/yjpark/winit/", branch = "touch-input_0.24.0" }
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader/", branch = "main" }
