[package]
name = "notation_tabs"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notation_tab = { path = "../../crates/notation_tab" }