[package]
name = "notation_audio"
version = "0.3.2"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://www.notation.fun"
repository = "https://github.com/notation-fun/notation"
description = "Fun notation - audio features"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[features]

[dependencies]
notation_model = { version = "0.3.2", path = "../notation_model" }
bevy = { version = "0.5.0", default-features = false }
bevy_kira_audio = "0.7.0"
ringbuf = "0.2.6"