[package]
name = "notation_viewer"
version = "0.3.3"
edition = "2021"
description = "Notation Viewer"

[package.metadata.bundle]
identifier = "fun.notation.viewer"
resources = ["assets"]

[features]
default = [
    "notation_bevy/midi",
]

native = [
    "notation_bevy/native",
    "notation_bevy/dsl",
]
dev = [
    "notation_bevy/dev",
    "native",
]

[dependencies]
notation_bevy = { path = "../../crates/notation_bevy" }
