[package]
name = "notation_viewer"
version = "0.2.3"
edition = "2021"
description = "Notation Viewer"

[package.metadata.bundle]
identifier = "fun.notation.viewer"
resources = ["assets"]

[features]
native = [
    "notation_bevy/native",
]
dev = [
    "notation_bevy/dev",
    "native",
]
inspector = [
    "notation_bevy/inspector",
    "native",
]

[dependencies]
notation_bevy = { version = "0.2.3", path = "../../crates/notation_bevy" }
