[package]
name = "notation_viewer"
version = "0.1.0"
edition = "2018"

[features]
dev = [
    "notation_bevy/dev",
    "notation_bevy/native",
]
inspector = [
    "notation_bevy/inspector",
    "notation_bevy/native",
]

[dependencies]
notation_bevy = { path = "../../crates/notation_bevy" }
