[package]
name = "notation_viewer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
notation_proto = { path = "../../crates/notation_proto" }
notation_bevy = { path = "../../crates/notation_bevy" }

bevy = "0.5.0"
# bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features = ["dynamic"]}

bevy_prototype_lyon = "0.3.1"

bevy_mod_picking = "0.4"
bevy-inspector-egui = "0.5.1"