[package]
name = "notation_kb"
version = "0.3.3"
edition = "2021"
description = "Fun Notation Knowledge Base"

[package.metadata.bundle]
identifier = "fun.notation.kb"
resources = ["assets"]

[features]
native = [
    "notation_bevy/native",
]
dev = [
    "notation_bevy/dev",
    "native",
]
inspector = [
    "notation_bevy/inspector",
    "native",
]

[dependencies]
notation_bevy = { version = "0.3.3", path = "../../crates/notation_bevy" }
