[package]
name = "notation_bevy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
notation_core = { path = "../notation_core" }
notation_proto = { path = "../notation_proto" }
notation_fretted = { path = "../notation_fretted" }
notation_guitar = { path = "../notation_guitar" }

serde = {version = "1.0.126", features = ["derive"]}
# https://github.com/serde-rs/serde/issues/1937
serde_arrays = "0.1.0"

bevy = "0.5.0"
bevy_prototype_lyon = "0.3.1"
bevy-inspector-egui = "0.5.1"

